# Generated by Django 5.0.3 on 2024-03-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf_name',
            field=models.CharField(default='pdf', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='course', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='pdf',
            field=models.FileField(default='courses/default.pdf', upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', through='app.LearningPath', to='app.student'),
        ),
    ]
