# Generated by Django 5.0.3 on 2024-03-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pdf_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='name_tag',
            field=models.CharField(default='course', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='pdf',
            field=models.FileField(null=True, upload_to='courses/'),
        ),
    ]
