# Generated by Django 5.0.3 on 2024-03-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_course_pdf_name_remove_course_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
