# Generated by Django 5.0.3 on 2024-03-31 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_teacher_courses_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='teacher',
            field=models.ForeignKey(related_name='learning_paths', to='app.Teacher', on_delete=models.CASCADE),
            preserve_default=False,
        ),
    ]

dependencies = [
    ('app', '0006_previous_migration'),
]