# Generated by Django 5.0.3 on 2024-04-01 16:34

import app.models
import django.db.models.deletion
from django.db import migrations, models

def copy_courses(apps, schema_editor):
    Teacher = apps.get_model('app', 'Teacher')
    for teacher in Teacher.objects.all():
        teacher.new_courses.set(teacher.courses.all())

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_learningpath_teacher_student_list_of_courses_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_courses),
    ]
