# Generated by Django 5.0.3 on 2024-04-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_course_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='new_courses',
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses_list',
            field=models.ManyToManyField(related_name='courses', through='app.LearningPath', to='app.course'),
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='pdfs',
            field=models.ManyToManyField(related_name='courses', to='app.pdf'),
        ),
    ]
