# Generated by Django 5.0.3 on 2024-04-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_course_pdf_remove_teacher_new_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pdfs',
            field=models.ManyToManyField(related_name='teachers', to='app.pdf'),
        ),
    ]
