# Generated by Django 5.0.3 on 2024-04-05 13:35

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(default=app.models.Teacher.get_default_teacher, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_tag',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='Default description', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='Default description', max_length=200),
        ),
        migrations.RemoveField(
            model_name='course',
            name='pdfs',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=app.models.Teacher.get_default_teacher, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.teacher'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='teacher',
            field=models.ForeignKey(default=app.models.Teacher.get_default_teacher, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.quiz'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.question'),
        ),
        migrations.AddField(
            model_name='course',
            name='pdfs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='app.pdf'),
        ),
    ]
