# Generated by Django 5.0.3 on 2024-04-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pdfs',
        ),
        migrations.AddField(
            model_name='course',
            name='pdfs',
            field=models.ManyToManyField(blank=True, related_name='courses', to='app.pdf'),
        ),
    ]
