# Generated by Django 5.0.3 on 2024-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_learningpath_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
