# Generated by Django 5.0.3 on 2024-04-14 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_course_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pdfs',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='app.pdf'),
        ),
        migrations.AddField(
            model_name='quizenrollment',
            name='date_enrolled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='quizenrollment',
            unique_together={('student', 'quiz')},
        ),
        migrations.AlterUniqueTogether(
            name='quizscore',
            unique_together={('student', 'quiz')},
        ),
    ]
