# Generated by Django 5.0.3 on 2024-04-14 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_quiz_pdfs_quizenrollment_date_enrolled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='app.teacher'),
        ),
        migrations.AddField(
            model_name='quizenrollment',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='quiz_list',
            field=models.ManyToManyField(related_name='quizzes', through='app.QuizEnrollment', to='app.quiz'),
        ),
    ]
