# Generated by Django 5.0.3 on 2024-04-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_quiz_teacher_quizenrollment_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='Default description', max_length=200),
        ),
    ]
