# Generated by Django 5.0.3 on 2024-04-14 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizenrollment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AlterField(
            model_name='quizenrollment',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_enrollments', to='app.teacher'),
        ),
    ]
