# Generated by Django 5.0.3 on 2024-04-15 00:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_quizenrollment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='pdfs',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='app.pdf'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='app.teacher'),
        ),
        migrations.CreateModel(
            name='TutorEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_enrollments', to='app.teacher')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutor')),
            ],
            options={
                'unique_together': {('student', 'tutor')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='tutor_list',
            field=models.ManyToManyField(related_name='tutors', through='app.TutorEnrollment', to='app.tutor'),
        ),
    ]
