# Generated by Django 5.0.3 on 2024-04-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_tutor_course_tutor_pdfs_alter_tutor_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quizzes',
            field=models.ManyToManyField(related_name='enrolled_students', to='app.quiz'),
        ),
        migrations.AddField(
            model_name='student',
            name='tutors',
            field=models.ManyToManyField(related_name='enrolled_students', to='app.tutor'),
        ),
    ]
