# Generated by Django 5.0.4 on 2024-05-03 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_student_quizzes_student_tutors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="pdfs",
        ),
    ]
