# Generated by Django 5.0.4 on 2024-05-03 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_remove_quiz_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="tutor_list",
        ),
        migrations.RemoveField(
            model_name="student",
            name="tutors",
        ),
        migrations.AlterUniqueTogether(
            name="tutorenrollment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tutorenrollment",
            name="student",
        ),
        migrations.RemoveField(
            model_name="tutorenrollment",
            name="teacher",
        ),
        migrations.DeleteModel(
            name="Tutor",
        ),
        migrations.DeleteModel(
            name="TutorEnrollment",
        ),
    ]