# Generated by Django 5.0.5 on 2024-05-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="level",
        ),
        migrations.AddField(
            model_name="score",
            name="level",
            field=models.CharField(default="beginner", max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="scores",
            field=models.ManyToManyField(related_name="students", to="app.score"),
        ),
    ]
