# Generated by Django 5.0.5 on 2024-05-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0032_score_answers_question_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="level",
            field=models.CharField(default="To be determined", max_length=20),
        ),
    ]
