# Generated by Django 5.0.5 on 2024-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0033_alter_score_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="session_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
