# Generated by Django 5.0.5 on 2024-06-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_question_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.CharField(default="beginner", max_length=20),
        ),
    ]
